CHECKPOINT_PATH="/app/show-and-tell/model/train"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="/app/mscoco/word_counts.txt"

# JPEG image file to caption.
IMAGE_FILE="/app/lobby.jpg"

# Build the inference binary.
bazel build -c opt //im2txt:run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
export CUDA_VISIBLE_DEVICES=""

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
